package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Records;
import ba.unsa.etf.rpr.exceptions.MyException;
import javafx.collections.ObservableList;

import java.sql.SQLException;
import java.util.List;

public class RecordManager {

    public List<Records> getAll() throws MyException {
        return DaoFactory.recordsDao().getAll();
    }

    public void add(Records rec) throws MyException {
        if (rec.getId() != 0){
            throw new MyException("Can't add record with ID. ID is autogenerated");
        }

        try{
            DaoFactory.recordsDao().add(rec);
        }catch (MyException e){
            throw new MyException(e.getMessage());
        }
    }

    public void update(Records rec) throws SQLException, MyException {
        DaoFactory.recordsDao().update(rec);
    }

    public Records getById(int id) throws MyException {
        return DaoFactory.recordsDao().getById(id);
    }
    public void delete(int id) throws MyException {
        DaoFactory.recordsDao().delete(id);
    }

    public ObservableList<String> allergies(int patientID) throws SQLException{
        return DaoFactory.recordsDao().allergies(patientID);
    }

    public Records findUserRecord(String username) throws MyException {
        return DaoFactory.recordsDao().findUserRecord(username);
    }
    public ObservableList<String> prescriptions(int patientID) throws SQLException{
        return DaoFactory.recordsDao().prescriptions(patientID);
    }
}
